export const CHANGE_PRODUCT = 'CHANGE PRODUCT';
export const CHANGE_ANIMATION_PLP = 'CHANGE ANIMATION PLP';
export const CHANGE_ANIMATION_IMAGE = 'CHANGE ANIMATION IMAGE';
export const CHANGE_TAB = 'CHANGE TAB';